runtime: python312

entrypoint: gunicorn -b :$PORT index:app

instance_class: F2

automatic_scaling:
  max_instances: 10
  min_idle_instances: 1
  max_idle_instances: 2
  target_cpu_utilization: 0.75
  target_throughput_utilization: 0.75

handlers:
- url: /.*
  script: auto

readiness_check:
  path: "/analyse"
  check_interval_sec: 60
  timeout_sec: 300

liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 300
  failure_threshold: 2
  success_threshold: 2
